version: "3.7"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - db
    ports: 
      - "3001:3001"
    expose: 
      - 3001
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
      - JWT_SECRET=mysecret
      - NODE_ENV=development
  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword